### ISSUE TITLE
About whether the gap package needs to be compiled.

### ISSUE THREAD

**Issue by hongyi-zhao** [feisele/orders#1]
According to the following description [here](https://github.com/gap-system/gap#obtaining-the-gap-package-distribution):

> In the latter case please note that make bootstrap-pkg-full only unpacks packages but does not build those of them that require compilation. You can change to the pkg directory and then call ../bin/BuildPackages.sh from there to build as many packages as possible.

It seems that some gap packages need to be compiled, while others don't. OTOH, according to the [following description](https://feisele.github.io/) of `orders` package:

>  just unpack this in the pkg/ directory of your [GAP](https://www.gap-system.org/) installation and use LoadPackage("orders");

So, this package belongs to the former, i.e., no compilation is needed. Considering that gap itself is a software developed based on `C/C++`, why are gap packages still divided into these two types?

Regards,
HZ

**Comment by feisele** [comment]
> why are gap packages still divided into these two types?

Because some GAP packages contain code or even separate executables that need to be compiled, while others (like this one) are written entirely in GAP. But that is really not a question about this package, but rather about the design of GAP in general.
